function Sigma = estimate_noise_vst3(data, b, VST_ABC)
% ESTIMATE_NOISE_VST3
% Estimate a spatial noise map using the Rice variance-stabilizing
% transformation method.
%
% This is a low-memory serial implementation of the original
% estimate_noise_vst3.m. It processes one spatial patch at a time instead
% of constructing large five-dimensional arrays for PARFOR.
%
% The following parts of the original algorithm are preserved:
%   1. Identical sliding-window locations
%   2. Identical patch dimensions
%   3. Identical Rice noise estimator
%   4. Identical overlap accumulation
%   5. Identical voxelwise averaging
%
% Usage:
%   Sigma = estimate_noise_vst3(data, b, VST_ABC)
%
% Returns
% -------
% Sigma:
%   Estimated noise map with dimensions [x, y, z].
%
% Expects
% -------
% data:
%   Magnitude MR image series with dimensions [x, y, z, M].
%
% b:
%   Spatial noise-estimation kernel. A scalar produces a b-by-b-by-b
%   kernel. A three-element vector specifies [bx, by, bz].
%
% VST_ABC:
%   Variance-stabilizing transform name or file. Default is 'B'.
%
% See also:
%   riceVST_sigmaEst
%   perform_riceVST3
%   perform_riceVST_EUI3
%
% Original copyright:
% Copyright (C) 2019 CMRR at UMN
% Author: Xiaoping Wu <xpwu@cmrr.umn.edu>
%
% Low-memory execution modification:
% Processes patches serially to avoid allocation and duplication of large
% five-dimensional arrays.

%% Input preparation

if isa(data, 'integer')
    data = single(data);
end

[sx, sy, sz, M] = size(data);

if ~exist('VST_ABC', 'var') || isempty(VST_ABC)
    VST_ABC = 'B';
end

if nargin < 2 || isempty(b)
    b = 5;
end

% Convert a scalar kernel size to [bx by bz].
if isscalar(b)
    b = repmat(b, 1, 3);
end

% Validate kernel specification.
if numel(b) ~= 3
    error('b must be a scalar or a three-element vector [bx by bz].');
end

b = double(b(:).');

bx = b(1);
by = b(2);
bz = b(3);

% Validate that kernel dimensions are positive integers.
if any(b < 1) || any(mod(b, 1) ~= 0)
    error('All kernel dimensions must be positive integers.');
end

% Validate that the kernel fits inside the input image.
if bx > sx || by > sy || bz > sz
    error(['The requested kernel [%d %d %d] exceeds the input image ', ...
           'dimensions [%d %d %d].'], ...
           bx, by, bz, sx, sy, sz);
end

% Sliding-window step. This matches the original implementation.
step = 1;

% Number of spatial samples in each patch.
N = bx * by * bz;

time0 = clock;

fprintf('--------start noise estimation --------\n');
fprintf('Input dimensions: %d x %d x %d x %d\n', sx, sy, sz, M);
fprintf('Noise-estimation kernel: %d x %d x %d\n', bx, by, bz);
fprintf('VST type: %s\n', VST_ABC);

%% Output accumulators

% Ys accumulates the noise estimate contributed by every overlapping patch.
Ys = zeros(sx, sy, sz);

% W records how many patch estimates contribute to each voxel.
W = zeros(sx, sy, sz);

%% Generate the same patch starting positions as the original code

indices_x = [1:step:sx-bx, sx-bx+1];
indices_y = [1:step:sy-by, sy-by+1];
indices_z = [1:step:sz-bz, sz-bz+1];

% Remove duplicate terminal positions if one was already generated by
% the regular step sequence.
indices_x = unique(indices_x, 'stable');
indices_y = unique(indices_y, 'stable');
indices_z = unique(indices_z, 'stable');

nPatchX = length(indices_x);
nPatchY = length(indices_y);
nPatchZ = length(indices_z);

fprintf('Patch starting positions: %d x %d x %d\n', ...
    nPatchX, nPatchY, nPatchZ);

fprintf('Total spatial patches: %d\n', ...
    nPatchX * nPatchY * nPatchZ);

disp('-> estimate noise using low-memory serial processing...');

%% Estimate noise one patch at a time

for ii = 1:nPatchX

    i = indices_x(ii);

    fprintf('--- x patch %d of %d, starting at x=%d ---\n', ...
        ii, nPatchX, i);

    for jj = 1:nPatchY

        j = indices_y(jj);

        for kk = 1:nPatchZ

            k = indices_z(kk);

            % Extract only the current local spatial patch.
            %
            % Dimensions before squeeze:
            %   [bx, by, bz, M]
            B1 = data( ...
                i:i+bx-1, ...
                j:j+by-1, ...
                k:k+bz-1, ...
                :);

            % Preserve the estimator used by the original fMRI repository.
            %
            % The original code uses:
            %   riceVST_sigmaEst(squeeze(B1), 0, 1, VST_ABC)
            %
            % printOut = 0
            % est_type = 1
            sig = riceVST_sigmaEst( ...
                squeeze(B1), ...
                0, ...
                1, ...
                VST_ABC);

            % Check that the patch estimator returned a usable scalar.
            if ~isscalar(sig) || ~isfinite(sig) || sig < 0
                error(['Invalid noise estimate at patch start ', ...
                       '[x=%d, y=%d, z=%d].'], ...
                       i, j, k);
            end

            % Accumulate the scalar patch noise estimate over all voxels
            % covered by this patch.
            Ys( ...
                i:i+bx-1, ...
                j:j+by-1, ...
                k:k+bz-1) = ...
            Ys( ...
                i:i+bx-1, ...
                j:j+by-1, ...
                k:k+bz-1) + sig;

            % Count this patch as one estimate for every covered voxel.
            W( ...
                i:i+bx-1, ...
                j:j+by-1, ...
                k:k+bz-1) = ...
            W( ...
                i:i+bx-1, ...
                j:j+by-1, ...
                k:k+bz-1) + 1;

        end
    end
end

%% Aggregate overlapping estimates

disp('-> aggregate overlapping noise estimations...');

if any(W(:) == 0)
    error(['At least one voxel did not receive a patch estimate. ', ...
           'Check the kernel dimensions and sliding-window indices.']);
end

Sigma = Ys ./ W;

%% Final validation and reporting

if any(~isfinite(Sigma(:)))
    error('The estimated Sigma map contains NaN or Inf values.');
end

fprintf('Estimated Sigma range: minimum=%g, maximum=%g\n', ...
    min(Sigma(:)), max(Sigma(:)));

fprintf('Total elapsed time = %f min\n\n', ...
    etime(clock, time0) / 60);

end